# Generated by Django 4.2.2 on 2023-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
