# Generated by Django 4.2.2 on 2023-06-30 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_posts_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
