# Generated by Django 4.2.2 on 2023-07-01 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_posts_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(default=None, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
